import fs from "node:fs/promises";
import path from "node:path";
import { jsString } from "../client-model.mjs";
import { writeMidnight } from "./midnight.mjs";
import { writeNoor } from "./noor.mjs";
import { writeLotusBarge } from "./lotus-barge.mjs";

function s(v) {
  return jsString(v);
}

function defaultSections(client, keys) {
  const out = {};
  for (const k of keys) {
    out[k] = client.sections?.[k] !== false;
  }
  return out;
}

/** @param {import('../client-model.mjs').ClientConfig} client */
async function writeGhibliPortrait(clientDir, client) {
  const bride = client.couple.bride;
  const groom = client.couple.groom;
  const sections = defaultSections(client, [
    "story",
    "countdown",
    "events",
    "venue",
    "gallery",
    "family",
  ]);
  const story = (client.story || [])
    .map(
      (item) => `    {
      title: ${s(item.title)},
      date: ${s(item.date || item.year || "")},
      text: ${s(item.text)},
    }`,
    )
    .join(",\n");

  const content = `/**
 * AUTO-GENERATED by InviteStory Control Centre.
 * Source of truth: client.json — re-apply from the Control Centre after edits.
 */

export interface StoryMilestone {
  title: string
  date: string
  text: string
}

export interface GalleryImage {
  src: string
  alt: string
}

export interface FamilySide {
  label: string
  title: string
  photo: string
  members: { name: string; relation: string }[]
}

export interface InvitationConfig {
  couple: {
    bride: string
    groom: string
    brideShort: string
    groomShort: string
  }
  weddingDate: string
  displayDate: string
  tagline: string
  hero: {
    childhoodBride: string
    childhoodGroom: string
    portraitBride: string
    portraitGroom: string
    bodyBride: string
    bodyGroom: string
  }
  story: StoryMilestone[]
  details: {
    ceremony: { title: string; venue: string; time: string; note: string }
    dressCode: string
  }
  venue: {
    name: string
    address: string
    mapQuery: string
  }
  gallery: GalleryImage[]
  families: { bride: FamilySide; groom: FamilySide }
  calendar: {
    title: string
    description: string
    durationHours: number
  }
  music: { src: string; label: string }
  theme: {
    gold: string
    background: string
    ink: string
    texture: "paper" | "plain"
  }
  fonts: { serif: string; script: string; sans: string }
  footer: { thanks: string; copyright: string }
  sections: {
    story: boolean
    countdown: boolean
    events: boolean
    venue: boolean
    gallery: boolean
    family: boolean
  }
}

const config: InvitationConfig = {
  couple: {
    bride: ${s(bride.full || bride.first)},
    groom: ${s(groom.full || groom.first)},
    brideShort: ${s(bride.short || bride.first)},
    groomShort: ${s(groom.short || groom.first)},
  },
  weddingDate: ${s(client.timing.primaryISO)},
  displayDate: ${s(client.timing.dateLabel)},
  tagline: ${s(client.copy.tagline || "")},
  hero: {
    childhoodBride: "images/childhood-bride.png",
    childhoodGroom: "images/childhood-groom.png",
    portraitBride: "images/portrait-bride.png",
    portraitGroom: "images/portrait-groom.png",
    bodyBride: "images/body-bride.png",
    bodyGroom: "images/body-groom.png",
  },
  story: [
${story}
  ],
  details: {
    ceremony: {
      title: "The Wedding Ceremony",
      venue: ${s(client.venue.name)},
      time: ${s(client.timing.timeLabel || "")},
      note: ${s(client.copy.invitationNote || "")},
    },
    dressCode: "Garden Formal",
  },
  venue: {
    name: ${s(client.venue.name)},
    address: ${s(client.venue.address)},
    mapQuery: ${s(client.venue.mapQuery)},
  },
  gallery: [
    { src: "images/gallery-1.png", alt: "Gallery 1" },
    { src: "images/gallery-2.png", alt: "Gallery 2" },
    { src: "images/gallery-3.png", alt: "Gallery 3" },
    { src: "images/gallery-4.png", alt: "Gallery 4" },
    { src: "images/gallery-5.png", alt: "Gallery 5" },
    { src: "images/gallery-6.png", alt: "Gallery 6" },
  ],
  families: {
    bride: {
      label: "The Bride's Family",
      title: ${s(bride.parents || "Bride's family")},
      photo: "images/family-bride.png",
      members: [{ name: ${s(bride.parents || "")}, relation: "Parents of the Bride" }],
    },
    groom: {
      label: "The Groom's Family",
      title: ${s(groom.parents || "Groom's family")},
      photo: "images/family-groom.png",
      members: [{ name: ${s(groom.parents || "")}, relation: "Parents of the Groom" }],
    },
  },
  calendar: {
    title: ${s(`${bride.short || bride.first} & ${groom.short || groom.first} — Wedding`)},
    description: ${s(client.copy.invitationNote || "")},
    durationHours: 4,
  },
  music: { src: "", label: "Our song" },
  theme: {
    gold: "#b98a4e",
    background: "#faf5ec",
    ink: "#46392c",
    texture: "paper",
  },
  fonts: {
    serif: "'Cormorant Garamond', Georgia, serif",
    script: "'Great Vibes', cursive",
    sans: "'Jost', 'Helvetica Neue', sans-serif",
  },
  footer: {
    thanks: ${s(client.copy.closing || "Thank you for celebrating with us")},
    copyright: ${s(`© ${new Date().getFullYear()} ${bride.short || bride.first} & ${groom.short || groom.first} · InviteStory`)},
  },
  sections: {
    story: ${sections.story},
    countdown: ${sections.countdown},
    events: ${sections.events},
    venue: ${sections.venue},
    gallery: ${sections.gallery},
    family: ${sections.family},
  },
}

export default config
`;
  await fs.writeFile(path.join(clientDir, "src/config.ts"), content, "utf8");
}

/** @param {import('../client-model.mjs').ClientConfig} client */
async function writeTamilThirumana(clientDir, client, configPath) {
  const bride = client.couple.bride;
  const groom = client.couple.groom;
  const [a, b] = client.couple.displayOrder || [groom.first, bride.first];
  const parts = client.timing.dateParts || {};
  const sections = defaultSections(client, [
    "countdown",
    "story",
    "events",
    "venue",
    "gallery",
    "contacts",
  ]);

  const events = (client.events || [])
    .map(
      (ev) => `    {
      id: ${s(ev.id)},
      name: ${s(ev.name)},
      description: ${s(ev.note || "")},
      start: ${s(ev.startISO)},
      end: ${s(ev.endISO || ev.startISO)},
      venue: ${s(ev.venue || client.venue.name)},
      address: ${s(ev.address || client.venue.address)},
      dressCode: ${s(ev.dressCode || "Traditional")},
      dressColor: "#c9922f",
    }`,
    )
    .join(",\n");

  const story = (client.story || [])
    .map(
      (item) => `    {
      year: ${s(item.year || "")},
      title: ${s(item.title)},
      text: ${s(item.text)},
    }`,
    )
    .join(",\n");

  const families = [
    `{ side: "Son of", names: ${s(groom.parents || "")} }`,
    `{ side: "Daughter of", names: ${s(bride.parents || "")} }`,
  ].join(",\n    ");

  const contacts = (client.contacts || [])
    .map(
      (c) =>
        `    { name: ${s(c.name)}, role: ${s(c.role || "")}, phone: ${s(c.phone)} }`,
    )
    .join(",\n");

  const content = `export type InviteEvent = {
  id: string;
  name: string;
  tamil?: string;
  description: string;
  start: string;
  end: string;
  venue: string;
  address: string;
  dressCode: string;
  dressColor: string;
};

export type InviteConfig = {
  brand: string;
  bride: string;
  groom: string;
  coupleLine: [string, string];
  hashtag: string;
  intro: string;
  weddingISO: string;
  dateLabel: {
    day: string;
    number: string;
    monthYear: string;
    time: string;
  };
  city: string;
  venue: {
    name: string;
    address: string;
    lat: number;
    lng: number;
    mapQuery: string;
  };
  events: InviteEvent[];
  story: { year: string; title: string; text: string }[];
  blessing: string;
  families: { side: string; names: string }[];
  contacts: { name: string; role: string; phone: string }[];
  sections: {
    countdown: boolean;
    story: boolean;
    events: boolean;
    venue: boolean;
    gallery: boolean;
    contacts: boolean;
  };
};

export const invite: InviteConfig = {
  brand: ${s(client.meta.brand || "InviteStory")},
  bride: ${s(bride.first)},
  groom: ${s(groom.first)},
  coupleLine: [${s(a)}, ${s(b)}],
  hashtag: ${s(client.meta.hashtag || "")},
  intro: ${s(client.copy.intro || "")},
  weddingISO: ${s(client.timing.primaryISO)},
  dateLabel: {
    day: ${s(parts.day || "")},
    number: ${s(parts.number || "")},
    monthYear: ${s(parts.monthYear || client.timing.dateLabel)},
    time: ${s(parts.time || client.timing.timeLabel || "")},
  },
  city: ${s(client.venue.city || "")},
  venue: {
    name: ${s(client.venue.name)},
    address: ${s(client.venue.address)},
    lat: ${Number(client.venue.lat) || 0},
    lng: ${Number(client.venue.lng) || 0},
    mapQuery: ${s(client.venue.mapQuery)},
  },
  events: [
${events}
  ],
  story: [
${story}
  ],
  blessing: ${s(client.copy.blessing || "")},
  families: [
    ${families}
  ],
  contacts: [
${contacts}
  ],
  sections: {
    countdown: ${sections.countdown},
    story: ${sections.story},
    events: ${sections.events},
    venue: ${sections.venue},
    gallery: ${sections.gallery},
    contacts: ${sections.contacts},
  },
};
`;
  await fs.writeFile(path.join(clientDir, configPath), content, "utf8");
}

/** @param {import('../client-model.mjs').ClientConfig} client */
async function writeRajwada(clientDir, client, configPath) {
  const bride = client.couple.bride;
  const groom = client.couple.groom;
  const sections = defaultSections(client, [
    "countdown",
    "story",
    "events",
    "venue",
    "gallery",
    "contacts",
  ]);
  const event = client.events?.[0];
  const story = (client.story || [])
    .map(
      (item, i) => `    {
      year: ${s(item.year || "")},
      title: ${s(item.title)},
      text: ${s(item.text)},
      image: story${["One", "Two", "Three"][i] || "One"},
    }`,
    )
    .join(",\n");

  const contacts = (client.contacts || [])
    .map((c) => `    { name: ${s(c.name)}, phone: ${s(c.phone)} }`)
    .join(",\n");

  const content = `/**
 * AUTO-GENERATED by InviteStory Control Centre from client.json
 */

import storyOne from "@/assets/story-1.jpg";
import storyTwo from "@/assets/story-2.jpg";
import storyThree from "@/assets/story-3.jpg";
import galleryOne from "@/assets/gallery-1.jpg";
import galleryTwo from "@/assets/gallery-2.jpg";
import galleryThree from "@/assets/gallery-3.jpg";
import galleryFour from "@/assets/gallery-4.jpg";

export type InviteEvent = {
  key: string;
  name: string;
  startsAt: string;
  durationMinutes: number;
  venue: string;
  address: string;
  dressCode: string;
  dressCodeColor: string;
  note?: string;
};

export const invitation = {
  couple: {
    groom: ${s(groom.first)},
    bride: ${s(bride.first)},
    monogram: ${s(client.meta.monogram || "")},
    hashtag: ${s(client.meta.hashtag || "")},
  },
  mainEvent: {
    title: ${s(`${groom.first} & ${bride.first} — Wedding Ceremony`)},
    startsAt: ${s(client.timing.primaryISO)},
    durationMinutes: ${event?.durationMinutes || 180},
    dateLabel: ${s(client.timing.dateLabel)},
    timeLabel: ${s(client.timing.timeLabel || "")},
  },
  families: {
    groomSide: {
      parents: ${s(groom.parents || "")},
      line: "request the pleasure of your esteemed presence at the wedding of their son",
    },
    brideSide: {
      parents: ${s(bride.parents || "")},
      line: "together with the family of their daughter",
    },
  },
  invitationNote: ${s(client.copy.invitationNote || "")},
  story: [
${story}
  ],
  events: [
    {
      key: "wedding",
      name: ${s(event?.name || "Wedding")},
      startsAt: ${s(event?.startISO || client.timing.primaryISO)},
      durationMinutes: ${event?.durationMinutes || 180},
      venue: ${s(event?.venue || client.venue.name)},
      address: ${s(event?.address || client.venue.address)},
      dressCode: ${s(event?.dressCode || "Traditional formals")},
      dressCodeColor: "#C9A84C",
      note: ${s(event?.note || "")},
    },
  ] satisfies InviteEvent[],
  venue: {
    name: ${s(client.venue.name)},
    address: ${s(client.venue.address)},
    lat: ${Number(client.venue.lat) || 0},
    lng: ${Number(client.venue.lng) || 0},
    directionsNote: ${s(client.venue.note || "")},
  },
  gallery: [
    { src: galleryOne, alt: "Gallery 1" },
    { src: galleryTwo, alt: "Gallery 2" },
    { src: galleryThree, alt: "Gallery 3" },
    { src: galleryFour, alt: "Gallery 4" },
  ],
  closing: {
    blessing: ${s(client.copy.blessing || "")},
    signOff: "With love and gratitude,",
  },
  contacts: [
${contacts}
  ],
  sections: {
    countdown: ${sections.countdown},
    story: ${sections.story},
    events: ${sections.events},
    venue: ${sections.venue},
    gallery: ${sections.gallery},
    contacts: ${sections.contacts},
  },
} as const;

export type Invitation = typeof invitation;
`;
  await fs.writeFile(path.join(clientDir, configPath), content, "utf8");
}

async function writeMarigold(clientDir, client, configPath) {
  const bride = client.couple.bride;
  const groom = client.couple.groom;
  const start = client.timing.primaryISO.replace(/\+05:30$/, "");
  const end =
    client.timing.endISO?.replace(/\+05:30$/, "") ||
    client.timing.primaryISO.replace(/T.*/, "T23:00:00");

  const content = `// AUTO-GENERATED by InviteStory Control Centre

export const invite = {
  bride: ${s(bride.first)},
  groom: ${s(groom.first)},
  dateLabel: ${s(client.timing.dateParts?.number ? `${client.timing.dateParts.number}.${(client.timing.dateParts.monthYear || "").slice(0, 3)}` : client.timing.dateLabel)},
  start: ${s(start)},
  end: ${s(end)},
  timeZoneOffset: "+05:30",
  dayLine: ${s(client.timing.dateLabel)},
  timeLine: ${s(client.timing.timeLabel || "")},
  eventTitle: ${s(`Wedding of ${groom.first} & ${bride.first}`)},
  invitationNote: ${s(client.copy.invitationNote || "")},
  venue: {
    name: ${s(client.venue.name)},
    address: ${s(client.venue.address)},
    query: ${s(client.venue.mapQuery)},
    lat: ${Number(client.venue.lat) || 0},
    lng: ${Number(client.venue.lng) || 0},
  },
  closing: ${s(client.copy.closing || "See you there")},
} as const;

export const mapsUrl = \`https://www.google.com/maps/search/?api=1&query=\${encodeURIComponent(
  invite.venue.query,
)}\`;

export const directionsUrl = \`https://www.google.com/maps/dir/?api=1&destination=\${encodeURIComponent(
  invite.venue.query,
)}\`;
`;
  await fs.writeFile(path.join(clientDir, configPath), content, "utf8");
}

async function writeWeddingData(clientDir, client, configPath) {
  const bride = client.couple.bride;
  const groom = client.couple.groom;
  const d = new Date(client.timing.primaryISO);
  const content = `export const wedding = {
  bride: {
    name: ${s(bride.full || bride.first)},
    parents: ${s(bride.parents || "")},
    note: ${s(client.copy.tagline || "")},
  },
  groom: {
    name: ${s(groom.full || groom.first)},
    parents: ${s(groom.parents || "")},
    note: ${s(client.copy.intro || "")},
  },
  invite: ${s(client.copy.invitationNote || "We warmly invite you to celebrate")},
  dateISO: ${s(client.timing.primaryISO)},
  endISO: ${s(client.timing.endISO || client.timing.primaryISO)},
  dateLabel: ${s(client.timing.dateParts?.monthYear || client.timing.dateLabel)},
  day: ${s(client.timing.dateParts?.number || String(d.getDate()))},
  timeLabel: ${s(client.timing.timeLabel || "")},
  venue: ${s(client.venue.name)},
  venueArea: ${s(client.venue.city || "")},
  mapsQuery: ${s(client.venue.mapQuery)},
  regards: ["Family"],
};

export const mapsUrl = \`https://www.google.com/maps/search/?api=1&query=\${encodeURIComponent(
  wedding.mapsQuery,
)}\`;
`;
  await fs.writeFile(path.join(clientDir, configPath), content, "utf8");
}

async function writeMeadow(clientDir, client, configPath) {
  const bride = client.couple.bride;
  const groom = client.couple.groom;
  const content = `export const wedding = {
  bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
  bismillahLatin: "In the name of Allah, the Most Gracious, the Most Merciful",
  ayah: "And of His signs is that He created for you mates from among yourselves, that you may find tranquillity in them; and He placed between you affection and mercy.",
  ayahRef: "Surah Ar-Rum 30:21",
  bride: {
    name: ${s(bride.first)},
    fullName: ${s(bride.full || bride.first)},
    line: ${s(bride.parents || "")},
    blurb: ${s(client.copy.tagline || "")},
    photo: "/wedding/bride.jpg",
  },
  groom: {
    name: ${s(groom.first)},
    fullName: ${s(groom.full || groom.first)},
    line: ${s(groom.parents || "")},
    blurb: ${s(client.copy.intro || "")},
    photo: "/wedding/groom.jpg",
  },
  heroArt: "/wedding/hero.jpg",
  dateISO: ${s(client.timing.primaryISO)},
  endISO: ${s(client.timing.endISO || client.timing.primaryISO)},
  dateLabel: ${s(client.timing.dateLabel)},
  timeLabel: ${s(client.timing.timeLabel || "")},
  venue: {
    name: ${s(client.venue.name)},
    address: ${s(client.venue.address)},
    mapsUrl: \`https://www.google.com/maps/search/?api=1&query=\${encodeURIComponent(${s(client.venue.mapQuery)})}\`,
    preview: "/wedding/map.jpg",
  },
  gallery: [
    "/wedding/gallery-1.jpg",
    "/wedding/gallery-2.jpg",
    "/wedding/gallery-3.jpg",
    "/wedding/gallery-4.jpg",
  ],
  closing: ${s(client.copy.closing || "")},
} as const;
`;
  await fs.writeFile(path.join(clientDir, configPath), content, "utf8");
}

async function writeGrandLine(clientDir, client, configPath) {
  const bride = client.couple.bride;
  const groom = client.couple.groom;
  const dateLocal = client.timing.primaryISO.replace(/\+05:30$/, "");
  const content = `export const wedding = {
  bride: {
    name: ${s(bride.first)},
    fullName: ${s(bride.full || bride.first)},
    epithet: "The Navigator",
    bounty: "1,500,000,000",
    intro: ${s(client.copy.tagline || "")},
    image: "/op-bride.png",
  },
  groom: {
    name: ${s(groom.first)},
    fullName: ${s(groom.full || groom.first)},
    epithet: "Captain",
    bounty: "1,500,000,001",
    intro: ${s(client.copy.intro || "")},
    image: "/op-groom.png",
  },
  date: ${s(dateLocal)},
  dateLabel: ${s(client.timing.dateLabel)},
  timeLabel: ${s(client.timing.timeLabel || "")},
  venue: {
    name: ${s(client.venue.name)},
    address: ${s(client.venue.address)},
    mapsQuery: ${s(client.venue.mapQuery)},
  },
  hashtag: ${s(client.meta.hashtag || "")},
} as const;

export const mapsUrl = \`https://www.google.com/maps/search/?api=1&query=\${encodeURIComponent(
  wedding.venue.mapsQuery,
)}\`;

function toIcsStamp(date) {
  return date.toISOString().replace(/[-:]/g, "").split(".")[0] + "Z";
}

export function buildIcs() {
  const start = new Date(wedding.date);
  const end = new Date(start.getTime() + 6 * 60 * 60 * 1000);
  return [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//Wedding Grand Fleet//EN",
    "BEGIN:VEVENT",
    \`UID:\${start.getTime()}@wedding-grand-fleet\`,
    \`DTSTAMP:\${toIcsStamp(new Date())}\`,
    \`DTSTART:\${toIcsStamp(start)}\`,
    \`DTEND:\${toIcsStamp(end)}\`,
    \`SUMMARY:\${wedding.bride.name} & \${wedding.groom.name} — Wedding\`,
    \`LOCATION:\${wedding.venue.name}, \${wedding.venue.address}\`,
    "DESCRIPTION:An InviteStory wedding adventure awaits.",
    "END:VEVENT",
    "END:VCALENDAR",
  ].join("\\r\\n");
}
`;
  await fs.writeFile(path.join(clientDir, configPath), content, "utf8");
}

async function writeSage(clientDir, client, configPath) {
  const bride = client.couple.bride;
  const groom = client.couple.groom;
  const story = (client.story || [])
    .map(
      (item, i) => `    {
      year: ${s(item.year || "")},
      title: ${s(item.title)},
      text: ${s(item.text)},
      image: ${s(`story-${(i % 3) + 1}`)},
    }`,
    )
    .join(",\n");
  const contacts = (client.contacts || [])
    .map((c) => `      { name: ${s(c.name)}, phone: ${s(c.phone)} }`)
    .join(",\n");

  const content = `/**
 * AUTO-GENERATED by InviteStory Control Centre
 */

export const invitation = {
  couple: {
    bride: ${s(bride.full || bride.first)},
    brideShort: ${s(bride.short || bride.first)},
    groom: ${s(groom.full || groom.first)},
    groomShort: ${s(groom.short || groom.first)},
    hashtag: ${s(client.meta.hashtag || "")},
  },
  invite: {
    kicker: ${s(client.copy.intro || "Together with their families")},
    line: "cordially invite you to their wedding",
  },
  event: {
    title: ${s(`The Wedding of ${bride.first} & ${groom.first}`)},
    startsAt: ${s(client.timing.primaryISO)},
    endsAt: ${s(client.timing.endISO || client.timing.primaryISO)},
    dateLabel: ${s(client.timing.dateLabel)},
    dayLabel: ${s(client.timing.dateParts?.day || "")},
    timeLabel: ${s(client.timing.timeLabel || "")},
    dressCode: "Indian festive",
    note: ${s(client.copy.invitationNote || "")},
  },
  venue: {
    name: ${s(client.venue.name)},
    address: ${s(client.venue.address)},
    mapsQuery: ${s(client.venue.mapQuery)},
    lat: ${Number(client.venue.lat) || 0},
    lng: ${Number(client.venue.lng) || 0},
  },
  story: [
${story}
  ],
  blessing: {
    line: ${s(client.copy.blessing || "")},
    translation: ${s(client.copy.closing || "")},
    source: "A blessing from both families",
  },
  footer: {
    families: ${s(`${bride.parents || ""} & ${groom.parents || ""}`)},
    contacts: [
${contacts}
    ],
  },
} as const;

export type Invitation = typeof invitation;
`;
  await fs.writeFile(path.join(clientDir, configPath), content, "utf8");
}

async function writeFlatVite(clientDir, client, configPath) {
  const bride = client.couple.bride;
  const groom = client.couple.groom;
  const event = client.events?.[0];
  const content = `// AUTO-GENERATED by InviteStory Control Centre

export interface WeddingEvent {
  id: string;
  title: string;
  telugu: string;
  dateLabel: string;
  timeLabel: string;
  startISO: string;
  endISO: string;
  note?: string;
  icon: "flower" | "hands" | "fire" | "sparkles";
}

export const wedding = {
  bride: ${s(bride.first)},
  groom: ${s(groom.first)},
  brideFirst: ${s(bride.short || bride.first)},
  groomFirst: ${s(groom.short || groom.first)},
  hashtag: ${s(client.meta.hashtag || "")},
  blessing: ${s(client.copy.blessing || "")},
  occasionTelugu: "శుభ ముహూర్తం",
  occasionLabel: "Wedding Muhurtham",
  weekdayLabel: ${s(client.timing.dateParts?.day || "")},
  dateLabel: ${s(client.timing.dateLabel)},
  muhurthamTimeLabel: ${s(client.timing.timeLabel || "")},
  muhurthamISO: ${s(client.timing.primaryISO)},
  venueName: ${s(client.venue.name)},
  venueLine1: ${s(client.venue.city || "")},
  venueLine2: ${s(client.venue.address)},
  venueAddress: ${s(client.venue.address)},
  mapsQuery: ${s(client.venue.mapQuery)},
  osmEmbed: "https://www.openstreetmap.org/export/embed.html?bbox=78.4%2C17.3%2C78.6%2C17.5&layer=mapnik",
  brideFamily: ${s(bride.parents || "")},
  groomFamily: ${s(groom.parents || "")},
  inviteLine1: ${s(client.copy.intro || "")},
  inviteLine2: ${s(client.copy.invitationNote || "")},
} as const;

export const events: WeddingEvent[] = [
  {
    id: "muhurtham",
    title: ${s(event?.name || "Muhurtham")},
    telugu: "ముహూర్తం",
    dateLabel: ${s(client.timing.dateLabel)},
    timeLabel: ${s(client.timing.timeLabel || "")},
    startISO: ${s(client.timing.primaryISO)},
    endISO: ${s(client.timing.endISO || client.timing.primaryISO)},
    note: ${s(event?.note || "")},
    icon: "fire",
  },
];

export const mainEvent: WeddingEvent = events[0];
`;
  await fs.writeFile(path.join(clientDir, configPath), content, "utf8");
}

async function writeLakePichola(clientDir, client, configPath) {
  const bride = client.couple.bride;
  const groom = client.couple.groom;
  const content = `export const WEDDING = {
  bride: ${s(bride.first)},
  groom: ${s(groom.first)},
  brideFamily: ${s(bride.parents || "")},
  groomFamily: ${s(groom.parents || "")},
  hashtag: ${s(client.meta.hashtag || "")},
  date: new Date(${s(client.timing.primaryISO)}),
  dateLabel: ${s(client.timing.dateLabel)},
  timeLabel: ${s(client.timing.timeLabel || "")},
  venue: ${s(`${client.venue.name}, ${client.venue.address}`)},
  mapQuery: ${s(client.venue.mapQuery)},
  mapsUrl: \`https://maps.google.com/?q=\${encodeURIComponent(${s(client.venue.mapQuery)})}\`,
}
`;
  await fs.writeFile(path.join(clientDir, configPath), content, "utf8");
}

/**
 * @param {string} clientDir
 * @param {import('../client-model.mjs').ClientConfig} client
 * @param {import('../registry.mjs').TemplateRegistryEntry} template
 */
export async function applyAdapter(clientDir, client, template) {
  if (!template.adapter || template.adapter === "none" || template.deferred) {
    throw new Error(
      `Template "${template.name}" is not editable yet (needs config extraction).`,
    );
  }

  const configPath = template.configPath;
  switch (template.adapter) {
    case "ghibli-portrait":
      return writeGhibliPortrait(clientDir, client);
    case "tamil-thirumana":
      return writeTamilThirumana(clientDir, client, configPath);
    case "rajwada-royale":
      return writeRajwada(clientDir, client, configPath);
    case "midnight-stargaze":
      return writeMidnight(clientDir, client, configPath);
    case "marigold-bhavan":
      return writeMarigold(clientDir, client, configPath);
    case "noor-e-zahra":
      return writeNoor(clientDir, client, configPath);
    case "wedding-data":
      return writeWeddingData(clientDir, client, configPath);
    case "meadow-nikah":
      return writeMeadow(clientDir, client, configPath);
    case "grand-line":
      return writeGrandLine(clientDir, client, configPath);
    case "sage-parchment":
      return writeSage(clientDir, client, configPath);
    case "flat-vite":
      return writeFlatVite(clientDir, client, configPath);
    case "lake-pichola":
      return writeLakePichola(clientDir, client, configPath);
    case "lotus-barge":
      return writeLotusBarge(clientDir, client, configPath);
    default:
      throw new Error(`Unknown adapter: ${template.adapter}`);
  }
}
