import fs from "node:fs/promises";
import path from "node:path";
import { jsString } from "../client-model.mjs";

const s = (value) => jsString(value);

/** @param {import('../client-model.mjs').ClientConfig} client */
export function lotusBargeConfigContent(client) {
  const bride = client.couple.bride;
  const groom = client.couple.groom;
  const event = client.events?.[0];
  const monthYear = client.timing.dateParts?.monthYear || "";
  const monthParts = monthYear.trim().split(/\s+/);
  const month = monthParts[0] || "";
  const year = monthParts.at(-1) || "";
  const sections = {
    events: client.sections?.events !== false,
    venue: client.sections?.venue !== false,
    countdown: client.sections?.countdown !== false,
  };

  return `// AUTO-GENERATED by InviteStory Control Centre
export const wedding = {
  bride: ${s(bride.first)},
  groom: ${s(groom.first)},
  brideFull: ${s(bride.full || bride.first)},
  groomFull: ${s(groom.full || groom.first)},
  brideParents: ${s(bride.parents || "")},
  groomParents: ${s(groom.parents || "")},
  familySignoff: ${s(`The ${bride.first} and ${groom.first} families`)},
  hashtag: ${s(client.meta.hashtag || "")},
  monogram: ${s(client.meta.monogram || `${groom.first[0] || "G"} ${bride.first[0] || "B"}`)},

  intro: {
    eyebrow: ${s(client.copy.intro || "A moonlit invitation")},
    title: ${s(client.copy.tagline || "An invitation carried by moonlight")},
    body: ${s(client.copy.invitationNote || "Follow the lotus barge to a celebration written in the stars.")},
    beginLabel: "Begin the Journey",
    enterLabel: "Enter the Celebration",
    tapHint: "Tap the glowing arch",
    playingLabel: "The journey begins",
    videoEnabled: ${Boolean(client.media?.["intro-video"])},
    videoTimeoutMs: 12000,
  },

  dateISO: ${s(client.timing.primaryISO)},
  dateLabel: ${s(client.timing.dateLabel)},
  timeLabel: ${s(client.timing.timeLabel || "")},
  dayLabel: ${s(client.timing.dateParts?.day || "")},
  dayNum: ${s(client.timing.dateParts?.number || "")},
  monthLabel: ${s(month)},
  yearLabel: ${s(year)},

  venue: {
    name: ${s(client.venue.name)},
    address: ${s(client.venue.address)},
    mapsQuery: ${s(client.venue.mapQuery)},
    landmark: ${s(client.venue.note || client.venue.city || "")},
    directionHint: "Tap to open turn-by-turn directions",
  },

  verse: {
    hindi: ${s(client.copy.verseHindi || "॥ शुभ विवाह ॥")},
    text: ${s(client.copy.verseText || client.copy.invitationNote || "")},
  },

  events: [
    {
      name: "Wedding",
      date: ${s(client.timing.dateLabel)},
      dayLabel: ${s(client.timing.dateParts?.day || "")},
      dayNum: ${s(client.timing.dateParts?.number || "")},
      monthLabel: ${s(monthYear)},
      time: ${s(client.timing.timeLabel || "")},
      venue: ${s(event?.venue || client.venue.name)},
      note: ${s(event?.note || client.copy.invitationNote || "")},
    },
  ],

  program: [
    { name: "Guest Arrival", time: ${s(client.timing.dateParts?.time || client.timing.timeLabel || "")} },
    { name: "Wedding Ceremony", time: "To follow" },
    { name: "Blessings", time: "To follow" },
    { name: "Dinner", time: "To follow" },
  ],

  assets: {
    introPoster: "./assets/lotus/intro-poster.webp",
    introEnd: "./assets/lotus/intro-end.webp",
    introVideo: "./assets/lotus/intro-journey.mp4",
    sky: "./assets/lotus/sky.webp",
    environment: "./assets/lotus/water-palace.webp",
    barge: "./assets/lotus/barge.png",
    couple: "./assets/lotus/couple.png",
    mandap: "./assets/lotus/lotus-mandap.png",
    foregroundLotus: "./assets/lotus/foreground-lotus.png",
    diya: "./assets/lotus/diya.png",
    petals: "./assets/lotus/floating-petals.png",
    frame: "./assets/lotus/ornamental-frame.png",
    social: "./assets/lotus/social-card.webp",
  },

  footer: {
    title: ${s(client.copy.closing || "Meet us under the moon")},
  },

  sections: {
    events: ${sections.events},
    venue: ${sections.venue},
    countdown: ${sections.countdown},
  },
};

export const googleCalendarUrl = () => {
  const start = new Date(wedding.dateISO);
  const end = new Date(start.getTime() + 5 * 60 * 60 * 1000);
  const fmt = (date) =>
    date.toISOString().replace(/-/g, "").replace(/:/g, "").replace(/\\.\\d{3}/, "").slice(0, 15) + "Z";
  const params = new URLSearchParams({
    action: "TEMPLATE",
    text: \`\${wedding.groom} weds \${wedding.bride}\`,
    dates: \`\${fmt(start)}/\${fmt(end)}\`,
    details: \`\${wedding.venue.name}, \${wedding.venue.address}. \${wedding.hashtag}\`,
    location: \`\${wedding.venue.name}, \${wedding.venue.address}\`,
  });
  return \`https://calendar.google.com/calendar/render?\${params.toString()}\`;
};

export const downloadICS = () => {
  const start = new Date(wedding.dateISO);
  const end = new Date(start.getTime() + 5 * 60 * 60 * 1000);
  const fmt = (date) =>
    date.toISOString().replace(/-/g, "").replace(/:/g, "").replace(/\\.\\d{3}/, "").slice(0, 15) + "Z";
  const ics = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//InviteStory//Wedding//EN",
    "BEGIN:VEVENT",
    \`UID:\${Date.now()}@invitestory\`,
    \`DTSTAMP:\${fmt(new Date())}\`,
    \`DTSTART:\${fmt(start)}\`,
    \`DTEND:\${fmt(end)}\`,
    \`SUMMARY:\${wedding.groom} weds \${wedding.bride}\`,
    \`DESCRIPTION:\${wedding.venue.name}, \${wedding.venue.address}\`,
    \`LOCATION:\${wedding.venue.name}\\\\, \${wedding.venue.address}\`,
    "END:VEVENT",
    "END:VCALENDAR",
  ].join("\\r\\n");
  const blob = new Blob([ics], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = \`\${wedding.groom}-\${wedding.bride}-wedding.ics\`;
  anchor.click();
  URL.revokeObjectURL(url);
};

export const mapsDirectionsUrl = \`https://www.google.com/maps/dir/?api=1&destination=\${encodeURIComponent(
  wedding.venue.mapsQuery,
)}\`;
`;
}

/**
 * @param {string} clientDir
 * @param {import('../client-model.mjs').ClientConfig} client
 * @param {string} configPath
 */
export async function writeLotusBarge(clientDir, client, configPath) {
  await fs.writeFile(
    path.join(clientDir, configPath),
    lotusBargeConfigContent(client),
    "utf8",
  );
}
