import fs from "node:fs/promises";
import path from "node:path";
import { jsString } from "../client-model.mjs";

const s = jsString;

function defaultSections(client, keys) {
  const out = {};
  for (const k of keys) out[k] = client.sections?.[k] !== false;
  return out;
}

export async function writeMidnight(clientDir, client, configPath) {
  const bride = client.couple.bride;
  const groom = client.couple.groom;
  const sections = defaultSections(client, ["events", "venue", "countdown"]);
  const event = client.events?.[0];
  const parts = client.timing.dateParts || {};

  const content = `// AUTO-GENERATED by InviteStory Control Centre from client.json

export const wedding = {
  bride: ${s(bride.first)},
  groom: ${s(groom.first)},
  brideFull: ${s(bride.full || bride.first)},
  groomFull: ${s(groom.full || groom.first)},
  brideParents: ${s(bride.parents || "")},
  groomParents: ${s(groom.parents || "")},
  hashtag: ${s(client.meta.hashtag || "")},
  monogram: ${s(client.meta.monogram || "")},
  dateISO: ${s(client.timing.primaryISO)},
  dateLabel: ${s(client.timing.dateLabel)},
  timeLabel: ${s(client.timing.timeLabel || "")},
  venue: {
    name: ${s(client.venue.name)},
    address: ${s(client.venue.address)},
    mapsQuery: ${s(client.venue.mapQuery)},
  },
  verse: {
    hindi: ${s(client.copy.verseHindi || "")},
    text: ${s(client.copy.verseText || client.copy.invitationNote || "")},
  },
  events: [
    {
      name: ${s(event?.name || "Wedding")},
      icon: "heart",
      date: ${s(client.timing.dateLabel)},
      dayLabel: ${s(parts.day || "")},
      dayNum: ${s(parts.number || "")},
      monthLabel: ${s(parts.monthYear || "")},
      time: ${s(client.timing.timeLabel || "")},
      venue: ${s(client.venue.name)},
      note: ${s(event?.note || "")},
    },
  ],
  program: [
    { name: "Baraat Arrival", time: "6:00 PM" },
    { name: "Jaimala", time: "6:45 PM" },
    { name: "Pheras & Sacred Vows", time: "7:00 PM" },
    { name: "Vidaai", time: "10:30 PM" },
  ],
  sections: {
    events: ${sections.events},
    venue: ${sections.venue},
    countdown: ${sections.countdown},
  },
};

export const googleCalendarUrl = () => {
  const start = new Date(wedding.dateISO);
  const end = new Date(start.getTime() + 7 * 60 * 60 * 1000);
  const fmt = (d) =>
    d.toISOString().replace(/[-:]|\\.\\d{3}/g, "").slice(0, 15) + "Z";
  const params = new URLSearchParams({
    action: "TEMPLATE",
    text: \`\${wedding.bride} weds \${wedding.groom}\`,
    dates: \`\${fmt(start)}/\${fmt(end)}\`,
    details: \`\${wedding.venue.name} — \${wedding.venue.address}. \${wedding.hashtag}\`,
    location: \`\${wedding.venue.name}, \${wedding.venue.address}\`,
  });
  return \`https://calendar.google.com/calendar/render?\${params.toString()}\`;
};

export const downloadICS = () => {
  const start = new Date(wedding.dateISO);
  const end = new Date(start.getTime() + 7 * 60 * 60 * 1000);
  const fmt = (d) =>
    d.toISOString().replace(/[-:.]/g, "").slice(0, 15) + "Z";
  const ics = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//InviteStory//Wedding//EN",
    "BEGIN:VEVENT",
    \`UID:\${Date.now()}@invitestory\`,
    \`DTSTAMP:\${fmt(new Date())}\`,
    \`DTSTART:\${fmt(start)}\`,
    \`DTEND:\${fmt(end)}\`,
    \`SUMMARY:\${wedding.bride} weds \${wedding.groom}\`,
    \`DESCRIPTION:\${wedding.venue.name} — \${wedding.venue.address}\`,
    \`LOCATION:\${wedding.venue.name}\\\\, \${wedding.venue.address}\`,
    "END:VEVENT",
    "END:VCALENDAR",
  ].join("\\r\\n");
  const blob = new Blob([ics], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = \`\${wedding.bride}-\${wedding.groom}-wedding.ics\`;
  a.click();
  URL.revokeObjectURL(url);
};

export const mapsUrl = \`https://www.google.com/maps/search/?api=1&query=\${encodeURIComponent(
  wedding.venue.mapsQuery
)}\`;

export const mapsEmbedUrl = \`https://www.google.com/maps?q=\${encodeURIComponent(
  wedding.venue.mapsQuery
)}&output=embed\`;

export const mapsDirectionsUrl = \`https://www.google.com/maps/dir/?api=1&destination=\${encodeURIComponent(
  wedding.venue.mapsQuery
)}\`;
`;

  await fs.writeFile(path.join(clientDir, configPath), content, "utf8");
}
