import path from "node:path";
import { fileURLToPath } from "node:url";
import { getEditorSchema } from "./editor-schemas.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const REPO_ROOT = path.resolve(__dirname, "../..");
export const CLIENTS_DIR = path.join(REPO_ROOT, "clients");
export const API_PORT = 8787;

/** @typedef {{ id: string, label: string, relativePath: string, aspect?: string }} MediaSlot */

/**
 * @typedef {object} TemplateRegistryEntry
 * @property {string} id
 * @property {string} folder
 * @property {string} name
 * @property {string} tagline
 * @property {string} vibe
 * @property {string[]} palette
 * @property {string} language
 * @property {string} weddingType
 * @property {string} highlight
 * @property {string} configPath
 * @property {string} adapter
 * @property {boolean} sectionsSupported
 * @property {string[]} sectionKeys
 * @property {MediaSlot[]} mediaSlots
 * @property {boolean} [deferred]
 * @property {import('./editor-schemas.mjs').EditorSection[]} [editorSections]
 */

/** @type {Omit<TemplateRegistryEntry, "editorSections">[]} */
const TEMPLATE_BASE = [
  {
    id: "rajwada-royale",
    folder: "template-rajwada-royale",
    name: "Rajwada Royale",
    tagline: "A palace door opens for your big day",
    vibe: "North-Indian royal palace",
    palette: ["#7B1E2B", "#C9A84C", "#F4E6CC"],
    language: "Hindi",
    weddingType: "Royal Palace",
    highlight: "Maroon + gold, diya petals, opening doors",
    configPath: "src/config/invitation.ts",
    adapter: "rajwada-royale",
    sectionsSupported: true,
    sectionKeys: ["countdown", "story", "events", "venue", "gallery", "contacts"],
    mediaSlots: [
      { id: "story-1", label: "Story 1", relativePath: "src/assets/story-1.jpg", aspect: "4:5" },
      { id: "story-2", label: "Story 2", relativePath: "src/assets/story-2.jpg", aspect: "4:5" },
      { id: "story-3", label: "Story 3", relativePath: "src/assets/story-3.jpg", aspect: "4:5" },
      { id: "gallery-1", label: "Gallery 1", relativePath: "src/assets/gallery-1.jpg", aspect: "1:1" },
      { id: "gallery-2", label: "Gallery 2", relativePath: "src/assets/gallery-2.jpg", aspect: "1:1" },
      { id: "gallery-3", label: "Gallery 3", relativePath: "src/assets/gallery-3.jpg", aspect: "1:1" },
      { id: "gallery-4", label: "Gallery 4", relativePath: "src/assets/gallery-4.jpg", aspect: "1:1" },
    ],
  },
  {
    id: "marigold-bhavan",
    folder: "template-marigold-bhavan",
    name: "Marigold Bhavan",
    tagline: "Sunshine, torans & tradition",
    vibe: "Classic Indian engagement",
    palette: ["#7A6E2A", "#D9A441", "#F1E6C4"],
    language: "Hindi",
    weddingType: "Hindu",
    highlight: "Olive + gold, paper envelope, sepia texture",
    configPath: "src/config/invite.ts",
    adapter: "marigold-bhavan",
    sectionsSupported: false,
    sectionKeys: ["countdown", "venue"],
    mediaSlots: [],
  },
  {
    id: "toran-telugu",
    folder: "template-toran-telugu",
    name: "Toran Telugu",
    tagline: "Banana leaves, brass lamps, big South-Indian warmth",
    vibe: "South Indian Telugu",
    palette: ["#5B1A1A", "#B68A3D", "#7A8C3A"],
    language: "Telugu",
    weddingType: "South Indian",
    highlight: "Maroon + brass + leaf, Telugu typography",
    configPath: "src/lib/invite.config.ts",
    adapter: "tamil-thirumana",
    sectionsSupported: false,
    sectionKeys: ["countdown", "story", "events", "venue", "gallery"],
    mediaSlots: [],
  },
  {
    id: "ghibli-selfie",
    folder: "template-ghibli-selfie",
    name: "Ghibli Selfie",
    tagline: "Hand-painted, animated, heartfelt",
    vibe: "Ghibli hand-painted",
    palette: ["#E2A89E", "#F4D9B5", "#7FB3A8"],
    language: "Urdu",
    weddingType: "Muslim Nikah",
    highlight: "Selfie shutter finale, paper-cut clouds",
    configPath: "",
    adapter: "none",
    sectionsSupported: false,
    sectionKeys: [],
    mediaSlots: [],
    deferred: true,
  },
  {
    id: "emerald-nikah",
    folder: "template-emerald-nikah",
    name: "Emerald Nikah",
    tagline: "Vows under emerald vines",
    vibe: "Emerald Islamic parchment",
    palette: ["#0E3B2E", "#D4AF37", "#F6EBC8"],
    language: "Urdu",
    weddingType: "Muslim Nikah",
    highlight: "Emerald + cream, roses & daisies",
    configPath: "",
    adapter: "none",
    sectionsSupported: false,
    sectionKeys: [],
    mediaSlots: [],
    deferred: true,
  },
  {
    id: "noor-e-zahra",
    folder: "template-noor-e-zahra",
    name: "Noor-e-Zahra",
    tagline: "The nikkah under a moonlit mandala",
    vibe: "Ivory + antique gold Islamic",
    palette: ["#F5EBC8", "#B58A2C", "#7C8B3F"],
    language: "Urdu",
    weddingType: "Muslim Nikah",
    highlight: "Mandala texture, Bismillah in Arabic",
    configPath: "src/lib/wedding.ts",
    adapter: "noor-e-zahra",
    sectionsSupported: false,
    sectionKeys: ["countdown", "venue"],
    mediaSlots: [],
  },
  {
    id: "royal-reception",
    folder: "template-royal-reception",
    name: "Royal Reception",
    tagline: "A grand reception under aurora lights",
    vibe: "Royal blue reception",
    palette: ["#1F2A6E", "#E8D49A", "#F4ECD8"],
    language: "Urdu",
    weddingType: "Muslim Walima",
    highlight: "Royal blue + ivory, aurora shimmer",
    configPath: "src/components/wedding/data.ts",
    adapter: "wedding-data",
    sectionsSupported: false,
    sectionKeys: ["countdown", "venue"],
    mediaSlots: [],
  },
  {
    id: "kerala-sands",
    folder: "template-kerala-sands",
    name: "Kerala Sands",
    tagline: "Temple bells, the sea, and jasmine",
    vibe: "Kerala traditional",
    palette: ["#F6EFD9", "#C29A48", "#7A6E40"],
    language: "Malayalam",
    weddingType: "South Indian",
    highlight: "Taj Malabar backdrop, ivory + gold",
    configPath: "src/components/wedding/data.ts",
    adapter: "wedding-data",
    sectionsSupported: false,
    sectionKeys: ["countdown", "venue"],
    mediaSlots: [],
  },
  {
    id: "meadow-nikah",
    folder: "template-meadow-nikah",
    name: "Meadow Nikah",
    tagline: "A nikah in a sunlit garden",
    vibe: "Garden outdoor Nikah",
    palette: ["#A4C8E1", "#A8C97F", "#E9C9D6"],
    language: "Urdu",
    weddingType: "Muslim Nikah",
    highlight: "Sky + meadow + blossom, envelope intro",
    configPath: "src/lib/wedding.ts",
    adapter: "meadow-nikah",
    sectionsSupported: false,
    sectionKeys: ["countdown", "gallery", "venue"],
    mediaSlots: [],
  },
  {
    id: "grand-line-voyage",
    folder: "template-grand-line-voyage",
    name: "Grand Line Voyage",
    tagline: "Set sail for forever",
    vibe: "Anime / One Piece adventure",
    palette: ["#1F8FCE", "#E0A82E", "#F5DC95"],
    language: "English",
    weddingType: "Beach",
    highlight: "Log Pose, sunset Goa, anime typography",
    configPath: "src/lib/wedding-config.ts",
    adapter: "grand-line",
    sectionsSupported: false,
    sectionKeys: ["countdown", "venue"],
    mediaSlots: [],
  },
  {
    id: "sage-parchment",
    folder: "template-sage-parchment",
    name: "Sage Parchment",
    tagline: "Two families, one parchment",
    vibe: "Sage + parchment classic",
    palette: ["#E9DDC4", "#A1B79B", "#5F6E5A"],
    language: "Hindi",
    weddingType: "Hindu",
    highlight: "Parchment + sage, open-gate intro",
    configPath: "src/config/invitation.ts",
    adapter: "sage-parchment",
    sectionsSupported: false,
    sectionKeys: ["countdown", "story", "venue", "gallery", "family"],
    mediaSlots: [],
  },
  {
    id: "ghibli-portrait",
    folder: "template-ghibli-portrait",
    name: "Ghibli Portrait",
    tagline: "From childhood sketches to the wedding aisle",
    vibe: "English Ghibli portrait",
    palette: ["#E3B89C", "#D6B47C", "#F2E1C5"],
    language: "English",
    weddingType: "Garden",
    highlight: "Ghibli portraits, watercolor florals",
    configPath: "src/config.ts",
    adapter: "ghibli-portrait",
    sectionsSupported: true,
    sectionKeys: ["story", "countdown", "events", "venue", "gallery", "family"],
    mediaSlots: [
      { id: "childhood-bride", label: "Childhood bride", relativePath: "public/images/childhood-bride.png", aspect: "1:1" },
      { id: "childhood-groom", label: "Childhood groom", relativePath: "public/images/childhood-groom.png", aspect: "1:1" },
      { id: "portrait-bride", label: "Portrait bride", relativePath: "public/images/portrait-bride.png", aspect: "3:4" },
      { id: "portrait-groom", label: "Portrait groom", relativePath: "public/images/portrait-groom.png", aspect: "3:4" },
      { id: "body-bride", label: "Body bride", relativePath: "public/images/body-bride.png", aspect: "3:4" },
      { id: "body-groom", label: "Body groom", relativePath: "public/images/body-groom.png", aspect: "3:4" },
      { id: "gallery-1", label: "Gallery 1", relativePath: "public/images/gallery-1.png", aspect: "1:1" },
      { id: "gallery-2", label: "Gallery 2", relativePath: "public/images/gallery-2.png", aspect: "1:1" },
      { id: "gallery-3", label: "Gallery 3", relativePath: "public/images/gallery-3.png", aspect: "1:1" },
      { id: "gallery-4", label: "Gallery 4", relativePath: "public/images/gallery-4.png", aspect: "1:1" },
      { id: "family-bride", label: "Bride family", relativePath: "public/images/family-bride.png", aspect: "4:5" },
      { id: "family-groom", label: "Groom family", relativePath: "public/images/family-groom.png", aspect: "4:5" },
    ],
  },
  {
    id: "rajwada-royale-alt",
    folder: "template-rajwada-royale-alt",
    name: "Rajwada Royale (Alt)",
    tagline: "Same palace, another couple",
    vibe: "North-Indian royal palace",
    palette: ["#7B1E2B", "#C9A84C", "#F4E6CC"],
    language: "Hindi",
    weddingType: "Royal Palace",
    highlight: "Alternate demo of Rajwada Royale",
    configPath: "src/config/invitation.ts",
    adapter: "rajwada-royale",
    sectionsSupported: false,
    sectionKeys: ["countdown", "story", "events", "venue", "gallery", "contacts"],
    mediaSlots: [
      { id: "story-1", label: "Story 1", relativePath: "src/assets/story-1.jpg", aspect: "4:5" },
      { id: "gallery-1", label: "Gallery 1", relativePath: "src/assets/gallery-1.jpg", aspect: "1:1" },
    ],
  },
  {
    id: "marigold-bhavan-alt",
    folder: "template-marigold-bhavan-alt",
    name: "Marigold Bhavan (Alt)",
    tagline: "Same bhavan, another couple",
    vibe: "Classic Indian engagement",
    palette: ["#7A6E2A", "#D9A441", "#F1E6C4"],
    language: "Hindi",
    weddingType: "Hindu",
    highlight: "Alternate demo of Marigold Bhavan",
    configPath: "src/config/invite.ts",
    adapter: "marigold-bhavan",
    sectionsSupported: false,
    sectionKeys: ["countdown", "venue"],
    mediaSlots: [],
  },
  {
    id: "rajmahal-palace",
    folder: "template-rajmahal-palace",
    name: "Rajmahal Palace",
    tagline: "Palace doors open onto forever",
    vibe: "Dark royal palace doors",
    palette: ["#3B0712", "#D9A441", "#F1DFB1"],
    language: "Hindi",
    weddingType: "Royal Palace",
    highlight: "Deep maroon + gold, opening doors",
    configPath: "src/config.ts",
    adapter: "midnight-stargaze",
    sectionsSupported: false,
    sectionKeys: ["events", "venue"],
    mediaSlots: [],
  },
  {
    id: "shubha-vivaham",
    folder: "template-shubha-vivaham",
    name: "Shubha Vivaham",
    tagline: "శుభ వివాహం - a Telugu muhurtham",
    vibe: "Telugu muhurtham with toran",
    palette: ["#6D1A2E", "#F6B93B", "#FFF9EF"],
    language: "Telugu",
    weddingType: "South Indian",
    highlight: "Marigold toran, Telugu shubha vivaham",
    configPath: "src/config.ts",
    adapter: "flat-vite",
    sectionsSupported: false,
    sectionKeys: ["countdown", "events", "venue"],
    mediaSlots: [],
  },
  {
    id: "midnight-stargaze",
    folder: "template-midnight-stargaze",
    name: "Midnight Stargaze",
    tagline: "Vows under a starlit sky",
    vibe: "Navy + gold midnight doors",
    palette: ["#0C0A24", "#E2C88F", "#F5EEE2"],
    language: "Hindi",
    weddingType: "Royal Palace",
    highlight: "Doors open under a sky of stars",
    configPath: "src/config.ts",
    adapter: "midnight-stargaze",
    sectionsSupported: true,
    sectionKeys: ["events", "venue", "countdown"],
    mediaSlots: [
      { id: "couple", label: "Couple", relativePath: "public/assets/couple.webp", aspect: "4:5" },
    ],
  },
  {
    id: "kalyana-mandapam",
    folder: "template-kalyana-mandapam",
    name: "Kalyana Mandapam",
    tagline: "The sacred muhurtham, beautifully told",
    vibe: "Telugu muhurtham mandapam",
    palette: ["#F7EFDB", "#7B1E1E", "#9A6B1F"],
    language: "Telugu",
    weddingType: "South Indian",
    highlight: "Telugu mandapam, parchment + kumkum",
    configPath: "src/config.ts",
    adapter: "flat-vite",
    sectionsSupported: false,
    sectionKeys: ["countdown", "events", "venue"],
    mediaSlots: [],
  },
  {
    id: "tamil-thirumana",
    folder: "template-tamil-thirumana",
    name: "Tamil Thirumana",
    tagline: "முகூர்த்தம் - the sacred knot at dawn",
    vibe: "Tamil wedding Coimbatore",
    palette: ["#5B1A1A", "#B68A3D", "#1F6B4A"],
    language: "Tamil",
    weddingType: "South Indian",
    highlight: "Tamil typography, banana leaf palette",
    configPath: "src/lib/invite.config.ts",
    adapter: "tamil-thirumana",
    sectionsSupported: true,
    sectionKeys: ["countdown", "story", "events", "venue", "gallery", "contacts"],
    mediaSlots: [],
  },
  {
    id: "lake-pichola",
    folder: "template-lake-pichola",
    name: "Lake Pichola Royal",
    tagline: "Palace reflections on Lake Pichola",
    vibe: "Royal palace by the lake",
    palette: ["#F2E4C3", "#B8912F", "#8A6A1F"],
    language: "Hindi",
    weddingType: "Royal Palace",
    highlight: "Gold floral texture, illustrated couple",
    configPath: "src/config.ts",
    adapter: "lake-pichola",
    sectionsSupported: false,
    sectionKeys: ["countdown", "venue"],
    mediaSlots: [],
  },
];

/** @type {TemplateRegistryEntry[]} */
export const TEMPLATES = TEMPLATE_BASE.map((t) => {
  const editorSections = getEditorSchema(t.id);
  const toggleKeys = editorSections
    .filter((s) => s.toggleKey)
    .map((s) => /** @type {string} */ (s.toggleKey));
  return {
    ...t,
    editorSections,
    // Prefer schema-derived toggles when present
    sectionKeys: toggleKeys.length ? toggleKeys : t.sectionKeys,
    sectionsSupported: toggleKeys.length > 0 || t.sectionsSupported,
  };
});

export function getTemplate(id) {
  return TEMPLATES.find((t) => t.id === id);
}

export function templatePath(folder) {
  return path.join(REPO_ROOT, folder);
}
