export const WEDDING = {
  bride: 'Ananya',
  groom: 'Aarav',
  brideFullName: 'Ananya Iyer',
  groomFullName: 'Aarav Sharma',
  brideFamily: 'daughter of Mr. Rajesh & Mrs. Meena Iyer',
  groomFamily: 'son of Mr. Vikram & Mrs. Sunita Sharma',
  hashtag: '#AaravWedsAnanya',
  phoneRsvp: '+919876543210',
  date: new Date('2026-02-21T19:00:00+05:30'),
  dateLabel: 'Saturday, 21 February 2026',
  timeLabel: '7:00 PM onwards',
  venue: 'The Royal Palms, Lake Pichola Road, Udaipur, Rajasthan 313001',
  venueShort: 'The Royal Palms, Lake Pichola',
  city: 'Udaipur, Rajasthan',
  mapQuery: 'Lake Pichola Udaipur Rajasthan',
  mapsUrl: 'https://maps.google.com/?q=Lake+Pichola+Udaipur',
  uberUrl: 'https://m.uber.com/ul/?action=setPickup&pickup=my_location&dropoff[formatted_address]=Lake%20Pichola%20Udaipur',
  weather: {
    temp: '24°C / 75°F',
    condition: 'Pleasant & Starlit Skies',
    forecast: 'Sunset at 6:38 PM with gentle lake breeze',
  },
  storySummary: 'Two souls brought together under the gilded skies of Udaipur, ready to embark on a lifelong voyage of love, harmony, and togetherness.',
  storyMilestones: [
    {
      year: '2022',
      title: 'The First Spark in Mumbai',
      subtitle: 'A chance meeting at Marine Drive',
      description: 'Amidst the Arabian sea breeze and monsoon drizzles, a shared cup of spiced cutting chai turned into an unforgettable four-hour conversation about art, dreams, and family.',
      icon: '✨',
      image: 'https://media.invitestory.in/lake-pichola-royal/assets/event_mehendi.jpg',
    },
    {
      year: '2024',
      title: 'The Proposal on Lake Pichola',
      subtitle: 'A sunset boat ride in Udaipur',
      description: 'With the silhouettes of Jag Mandir reflecting upon the shimmering amber waters and Shehnai melodies floating from the shore, Aarav went down on one knee with a ring carved in rose gold.',
      icon: '💍',
      image: 'https://media.invitestory.in/lake-pichola-royal/assets/hero_twilight.jpg',
    },
    {
      year: '2026',
      title: 'The Sacred Vows',
      subtitle: 'Where their story enters forever',
      description: 'Returning to the sacred waters of Lake Pichola to tie their destinies with Vedic chants, royal feasts, and the blessings of everyone they hold dear.',
      icon: '🪔',
      image: 'https://media.invitestory.in/lake-pichola-royal/assets/event_vivah.jpg',
    },
  ],
  events: [
    {
      id: 'mehendi',
      day: 'Day 1',
      title: 'Mehendi & High Tea',
      date: 'Friday, 20 February 2026',
      isoDate: '2026-02-20T15:30:00+05:30',
      time: '3:30 PM Onwards',
      venue: 'The Lakeside Courtyard, Royal Palms',
      dressCode: 'Vibrant Florals & Pastel Heritage',
      icon: '🌿',
      image: 'https://media.invitestory.in/lake-pichola-royal/assets/event_mehendi.jpg',
      tag: 'Celebration of Henna & Folk Beats',
      description: 'An afternoon of intricate bridal henna, traditional Rajasthani Ghoomar folk performances, artisanal street delicacies, and royal high tea overlooking the calm waters.',
      colors: [
        { name: 'Mint Green', hex: '#A8D5BA' },
        { name: 'Marigold Yellow', hex: '#F6BE3C' },
        { name: 'Peach Blossom', hex: '#FFB7A1' },
        { name: 'Ivory Gold', hex: '#F3E8CB' },
      ],
    },
    {
      id: 'sangeet',
      day: 'Day 1',
      title: 'Sangeet Royale',
      date: 'Friday, 20 February 2026',
      isoDate: '2026-02-20T19:30:00+05:30',
      time: '7:30 PM Onwards',
      venue: 'Grand Pichola Ballroom & Terraces',
      dressCode: 'Glamour, Shimmer & Indo-Western',
      icon: '🎶',
      image: 'https://media.invitestory.in/lake-pichola-royal/assets/event_sangeet.jpg',
      tag: 'Music, Dance & Champagne',
      description: 'A dazzling night of high-energy family dance battles, live Bollywood fusion band, celebratory cocktails, and culinary masterpieces under the starlit sky.',
      colors: [
        { name: 'Midnight Navy', hex: '#1B2A4A' },
        { name: 'Emerald Gem', hex: '#1B4332' },
        { name: '24K Gold', hex: '#D4AF37' },
        { name: 'Wine Velvet', hex: '#631D28' },
      ],
    },
    {
      id: 'vivah',
      day: 'Day 2',
      title: 'Shubh Vivah & Pheras',
      date: 'Saturday, 21 February 2026',
      isoDate: '2026-02-21T17:30:00+05:30',
      time: '5:30 PM Baraat • 7:00 PM Varmala & Pheras',
      venue: 'The Palatial Mandap Terrace',
      dressCode: 'Royal Traditional Heritage',
      icon: '💍',
      image: 'https://media.invitestory.in/lake-pichola-royal/assets/event_vivah.jpg',
      tag: 'Sacred Vows & Sunset Pheras',
      description: 'Witness the grand royal Baraat procession followed by the sacred seven vows (Saat Phere) around the holy fire as twilight paints Lake Pichola in gold.',
      colors: [
        { name: 'Royal Crimson', hex: '#871926' },
        { name: 'Imperial Gold', hex: '#B8912F' },
        { name: 'Kanjeevaram Ochre', hex: '#D68910' },
        { name: 'Pure Raw Silk', hex: '#FAF6EE' },
      ],
    },
    {
      id: 'reception',
      day: 'Day 3',
      title: 'The Grand Reception',
      date: 'Sunday, 22 February 2026',
      isoDate: '2026-02-22T19:30:00+05:30',
      time: '7:30 PM Onwards',
      venue: 'The Royal Palace Lawns',
      dressCode: 'Black Tie / Royal Formal',
      icon: '🥂',
      image: 'https://media.invitestory.in/lake-pichola-royal/assets/event_reception.jpg',
      tag: 'Gala Dinner & Live Symphony',
      description: 'An enchanting evening of fine multi-course dining, royal toasts, cake cutting ceremony, and live symphony orchestral performances to honor the newlyweds.',
      colors: [
        { name: 'Classic Black', hex: '#1C1C1E' },
        { name: 'Champagne Gold', hex: '#E6D5B8' },
        { name: 'Deep Ruby', hex: '#4A0E17' },
        { name: 'Sterling Platinum', hex: '#E5E7EB' },
      ],
    },
  ],
  gallery: [
    { title: 'Sunset Mandap at Pichola', image: 'https://media.invitestory.in/lake-pichola-royal/assets/event_vivah.jpg', tag: 'Sacred Vivah' },
    { title: 'The Royal Grand Reception', image: 'https://media.invitestory.in/lake-pichola-royal/assets/event_reception.jpg', tag: 'Gala Evening' },
    { title: 'Sangeet Under the Stars', image: 'https://media.invitestory.in/lake-pichola-royal/assets/event_sangeet.jpg', tag: 'Sangeet Royale' },
    { title: 'Lakeside Mehendi Courtyard', image: 'https://media.invitestory.in/lake-pichola-royal/assets/event_mehendi.jpg', tag: 'Mehendi & High Tea' },
    { title: 'Lake Pichola Royal Palace', image: 'https://media.invitestory.in/lake-pichola-royal/assets/hero_twilight.jpg', tag: 'Palatial Heritage' },
    { title: 'Aarav & Ananya Portrait', image: 'https://media.invitestory.in/lake-pichola-royal/assets/royal-couple.jpg', tag: 'Royal Couple' },
  ],
  hospitality: {
    airport: 'Maharana Pratap Airport (UDR) — 28 km / 45 min drive',
    railway: 'Udaipur City Railway Station — 4.5 km / 15 min drive',
    shuttle: 'Dedicated royal luxury chauffeurs available round the clock for all guests.',
    concierge: 'Wedding Concierge Desk at Hotel Lobby (+91 98765 00000)',
    checkIn: 'Hotel Check-in: 12:00 PM | Early check-in available upon prior notice',
  },
}
